#ifndef __odbctrac_h__
#define __odbctrac_h__

	#define naked __declspec(naked)
	#define inline __forceinline


	extern FARPROC mProcs[];
	inline naked int call_FireVSDebugEvent() { __asm { jmp dword ptr [ mProcs + 0 * 4 ] } }
	inline naked int call_TraceCloseLogFile() { __asm { jmp dword ptr [ mProcs + 1 * 4 ] } }
	inline naked int call_TraceOpenLogFile() { __asm { jmp dword ptr [ mProcs + 2 * 4 ] } }
	inline naked int call_TraceReturn() { __asm { jmp dword ptr [ mProcs + 3 * 4 ] } }
	inline naked int call_TraceSQLAllocConnect() { __asm { jmp dword ptr [ mProcs + 4 * 4 ] } }
	inline naked int call_TraceSQLAllocEnv() { __asm { jmp dword ptr [ mProcs + 5 * 4 ] } }
	inline naked int call_TraceSQLAllocHandle() { __asm { jmp dword ptr [ mProcs + 6 * 4 ] } }
	inline naked int call_TraceSQLAllocHandleStd() { __asm { jmp dword ptr [ mProcs + 7 * 4 ] } }
	inline naked int call_TraceSQLAllocHandleStdW() { __asm { jmp dword ptr [ mProcs + 8 * 4 ] } }
	inline naked int call_TraceSQLAllocStmt() { __asm { jmp dword ptr [ mProcs + 9 * 4 ] } }
	inline naked int call_TraceSQLBindCol() { __asm { jmp dword ptr [ mProcs + 10 * 4 ] } }
	inline naked int call_TraceSQLBindParam() { __asm { jmp dword ptr [ mProcs + 11 * 4 ] } }
	inline naked int call_TraceSQLBindParameter() { __asm { jmp dword ptr [ mProcs + 12 * 4 ] } }
	inline naked int call_TraceSQLBrowseConnect() { __asm { jmp dword ptr [ mProcs + 13 * 4 ] } }
	inline naked int call_TraceSQLBrowseConnectW() { __asm { jmp dword ptr [ mProcs + 14 * 4 ] } }
	inline naked int call_TraceSQLBulkOperations() { __asm { jmp dword ptr [ mProcs + 15 * 4 ] } }
	inline naked int call_TraceSQLCancel() { __asm { jmp dword ptr [ mProcs + 16 * 4 ] } }
	inline naked int call_TraceSQLCancelHandle() { __asm { jmp dword ptr [ mProcs + 17 * 4 ] } }
	inline naked int call_TraceSQLCloseCursor() { __asm { jmp dword ptr [ mProcs + 18 * 4 ] } }
	inline naked int call_TraceSQLColAttribute() { __asm { jmp dword ptr [ mProcs + 19 * 4 ] } }
	inline naked int call_TraceSQLColAttributes() { __asm { jmp dword ptr [ mProcs + 20 * 4 ] } }
	inline naked int call_TraceSQLColAttributesW() { __asm { jmp dword ptr [ mProcs + 21 * 4 ] } }
	inline naked int call_TraceSQLColAttributeW() { __asm { jmp dword ptr [ mProcs + 22 * 4 ] } }
	inline naked int call_TraceSQLColumnPrivileges() { __asm { jmp dword ptr [ mProcs + 23 * 4 ] } }
	inline naked int call_TraceSQLColumnPrivilegesW() { __asm { jmp dword ptr [ mProcs + 24 * 4 ] } }
	inline naked int call_TraceSQLColumns() { __asm { jmp dword ptr [ mProcs + 25 * 4 ] } }
	inline naked int call_TraceSQLColumnsW() { __asm { jmp dword ptr [ mProcs + 26 * 4 ] } }
	inline naked int call_TraceSQLConnect() { __asm { jmp dword ptr [ mProcs + 27 * 4 ] } }
	inline naked int call_TraceSQLConnectW() { __asm { jmp dword ptr [ mProcs + 28 * 4 ] } }
	inline naked int call_TraceSQLCopyDesc() { __asm { jmp dword ptr [ mProcs + 29 * 4 ] } }
	inline naked int call_TraceSQLDataSources() { __asm { jmp dword ptr [ mProcs + 30 * 4 ] } }
	inline naked int call_TraceSQLDataSourcesW() { __asm { jmp dword ptr [ mProcs + 31 * 4 ] } }
	inline naked int call_TraceSQLDescribeCol() { __asm { jmp dword ptr [ mProcs + 32 * 4 ] } }
	inline naked int call_TraceSQLDescribeColW() { __asm { jmp dword ptr [ mProcs + 33 * 4 ] } }
	inline naked int call_TraceSQLDescribeParam() { __asm { jmp dword ptr [ mProcs + 34 * 4 ] } }
	inline naked int call_TraceSQLDisconnect() { __asm { jmp dword ptr [ mProcs + 35 * 4 ] } }
	inline naked int call_TraceSQLDriverConnect() { __asm { jmp dword ptr [ mProcs + 36 * 4 ] } }
	inline naked int call_TraceSQLDriverConnectW() { __asm { jmp dword ptr [ mProcs + 37 * 4 ] } }
	inline naked int call_TraceSQLDrivers() { __asm { jmp dword ptr [ mProcs + 38 * 4 ] } }
	inline naked int call_TraceSQLDriversW() { __asm { jmp dword ptr [ mProcs + 39 * 4 ] } }
	inline naked int call_TraceSQLEndTran() { __asm { jmp dword ptr [ mProcs + 40 * 4 ] } }
	inline naked int call_TraceSQLError() { __asm { jmp dword ptr [ mProcs + 41 * 4 ] } }
	inline naked int call_TraceSQLErrorW() { __asm { jmp dword ptr [ mProcs + 42 * 4 ] } }
	inline naked int call_TraceSQLExecDirect() { __asm { jmp dword ptr [ mProcs + 43 * 4 ] } }
	inline naked int call_TraceSQLExecDirectW() { __asm { jmp dword ptr [ mProcs + 44 * 4 ] } }
	inline naked int call_TraceSQLExecute() { __asm { jmp dword ptr [ mProcs + 45 * 4 ] } }
	inline naked int call_TraceSQLExtendedFetch() { __asm { jmp dword ptr [ mProcs + 46 * 4 ] } }
	inline naked int call_TraceSQLFetch() { __asm { jmp dword ptr [ mProcs + 47 * 4 ] } }
	inline naked int call_TraceSQLFetchScroll() { __asm { jmp dword ptr [ mProcs + 48 * 4 ] } }
	inline naked int call_TraceSQLForeignKeys() { __asm { jmp dword ptr [ mProcs + 49 * 4 ] } }
	inline naked int call_TraceSQLForeignKeysW() { __asm { jmp dword ptr [ mProcs + 50 * 4 ] } }
	inline naked int call_TraceSQLFreeConnect() { __asm { jmp dword ptr [ mProcs + 51 * 4 ] } }
	inline naked int call_TraceSQLFreeEnv() { __asm { jmp dword ptr [ mProcs + 52 * 4 ] } }
	inline naked int call_TraceSQLFreeHandle() { __asm { jmp dword ptr [ mProcs + 53 * 4 ] } }
	inline naked int call_TraceSQLFreeStmt() { __asm { jmp dword ptr [ mProcs + 54 * 4 ] } }
	inline naked int call_TraceSQLGetConnectAttr() { __asm { jmp dword ptr [ mProcs + 55 * 4 ] } }
	inline naked int call_TraceSQLGetConnectAttrW() { __asm { jmp dword ptr [ mProcs + 56 * 4 ] } }
	inline naked int call_TraceSQLGetConnectOption() { __asm { jmp dword ptr [ mProcs + 57 * 4 ] } }
	inline naked int call_TraceSQLGetConnectOptionW() { __asm { jmp dword ptr [ mProcs + 58 * 4 ] } }
	inline naked int call_TraceSQLGetCursorName() { __asm { jmp dword ptr [ mProcs + 59 * 4 ] } }
	inline naked int call_TraceSQLGetCursorNameW() { __asm { jmp dword ptr [ mProcs + 60 * 4 ] } }
	inline naked int call_TraceSQLGetData() { __asm { jmp dword ptr [ mProcs + 61 * 4 ] } }
	inline naked int call_TraceSQLGetDescField() { __asm { jmp dword ptr [ mProcs + 62 * 4 ] } }
	inline naked int call_TraceSQLGetDescFieldW() { __asm { jmp dword ptr [ mProcs + 63 * 4 ] } }
	inline naked int call_TraceSQLGetDescRec() { __asm { jmp dword ptr [ mProcs + 64 * 4 ] } }
	inline naked int call_TraceSQLGetDescRecW() { __asm { jmp dword ptr [ mProcs + 65 * 4 ] } }
	inline naked int call_TraceSQLGetDiagField() { __asm { jmp dword ptr [ mProcs + 66 * 4 ] } }
	inline naked int call_TraceSQLGetDiagFieldW() { __asm { jmp dword ptr [ mProcs + 67 * 4 ] } }
	inline naked int call_TraceSQLGetDiagRec() { __asm { jmp dword ptr [ mProcs + 68 * 4 ] } }
	inline naked int call_TraceSQLGetDiagRecW() { __asm { jmp dword ptr [ mProcs + 69 * 4 ] } }
	inline naked int call_TraceSQLGetEnvAttr() { __asm { jmp dword ptr [ mProcs + 70 * 4 ] } }
	inline naked int call_TraceSQLGetFunctions() { __asm { jmp dword ptr [ mProcs + 71 * 4 ] } }
	inline naked int call_TraceSQLGetInfo() { __asm { jmp dword ptr [ mProcs + 72 * 4 ] } }
	inline naked int call_TraceSQLGetInfoW() { __asm { jmp dword ptr [ mProcs + 73 * 4 ] } }
	inline naked int call_TraceSQLGetStmtAttr() { __asm { jmp dword ptr [ mProcs + 74 * 4 ] } }
	inline naked int call_TraceSQLGetStmtAttrW() { __asm { jmp dword ptr [ mProcs + 75 * 4 ] } }
	inline naked int call_TraceSQLGetStmtOption() { __asm { jmp dword ptr [ mProcs + 76 * 4 ] } }
	inline naked int call_TraceSQLGetTypeInfo() { __asm { jmp dword ptr [ mProcs + 77 * 4 ] } }
	inline naked int call_TraceSQLGetTypeInfoW() { __asm { jmp dword ptr [ mProcs + 78 * 4 ] } }
	inline naked int call_TraceSQLMoreResults() { __asm { jmp dword ptr [ mProcs + 79 * 4 ] } }
	inline naked int call_TraceSQLNativeSql() { __asm { jmp dword ptr [ mProcs + 80 * 4 ] } }
	inline naked int call_TraceSQLNativeSqlW() { __asm { jmp dword ptr [ mProcs + 81 * 4 ] } }
	inline naked int call_TraceSQLNumParams() { __asm { jmp dword ptr [ mProcs + 82 * 4 ] } }
	inline naked int call_TraceSQLNumResultCols() { __asm { jmp dword ptr [ mProcs + 83 * 4 ] } }
	inline naked int call_TraceSQLParamData() { __asm { jmp dword ptr [ mProcs + 84 * 4 ] } }
	inline naked int call_TraceSQLParamOptions() { __asm { jmp dword ptr [ mProcs + 85 * 4 ] } }
	inline naked int call_TraceSQLPrepare() { __asm { jmp dword ptr [ mProcs + 86 * 4 ] } }
	inline naked int call_TraceSQLPrepareW() { __asm { jmp dword ptr [ mProcs + 87 * 4 ] } }
	inline naked int call_TraceSQLPrimaryKeys() { __asm { jmp dword ptr [ mProcs + 88 * 4 ] } }
	inline naked int call_TraceSQLPrimaryKeysW() { __asm { jmp dword ptr [ mProcs + 89 * 4 ] } }
	inline naked int call_TraceSQLProcedureColumns() { __asm { jmp dword ptr [ mProcs + 90 * 4 ] } }
	inline naked int call_TraceSQLProcedureColumnsW() { __asm { jmp dword ptr [ mProcs + 91 * 4 ] } }
	inline naked int call_TraceSQLProcedures() { __asm { jmp dword ptr [ mProcs + 92 * 4 ] } }
	inline naked int call_TraceSQLProceduresW() { __asm { jmp dword ptr [ mProcs + 93 * 4 ] } }
	inline naked int call_TraceSQLPutData() { __asm { jmp dword ptr [ mProcs + 94 * 4 ] } }
	inline naked int call_TraceSQLRowCount() { __asm { jmp dword ptr [ mProcs + 95 * 4 ] } }
	inline naked int call_TraceSQLSetConnectAttr() { __asm { jmp dword ptr [ mProcs + 96 * 4 ] } }
	inline naked int call_TraceSQLSetConnectAttrW() { __asm { jmp dword ptr [ mProcs + 97 * 4 ] } }
	inline naked int call_TraceSQLSetConnectOption() { __asm { jmp dword ptr [ mProcs + 98 * 4 ] } }
	inline naked int call_TraceSQLSetConnectOptionW() { __asm { jmp dword ptr [ mProcs + 99 * 4 ] } }
	inline naked int call_TraceSQLSetCursorName() { __asm { jmp dword ptr [ mProcs + 100 * 4 ] } }
	inline naked int call_TraceSQLSetCursorNameW() { __asm { jmp dword ptr [ mProcs + 101 * 4 ] } }
	inline naked int call_TraceSQLSetDescField() { __asm { jmp dword ptr [ mProcs + 102 * 4 ] } }
	inline naked int call_TraceSQLSetDescFieldW() { __asm { jmp dword ptr [ mProcs + 103 * 4 ] } }
	inline naked int call_TraceSQLSetDescRec() { __asm { jmp dword ptr [ mProcs + 104 * 4 ] } }
	inline naked int call_TraceSQLSetEnvAttr() { __asm { jmp dword ptr [ mProcs + 105 * 4 ] } }
	inline naked int call_TraceSQLSetParam() { __asm { jmp dword ptr [ mProcs + 106 * 4 ] } }
	inline naked int call_TraceSQLSetPos() { __asm { jmp dword ptr [ mProcs + 107 * 4 ] } }
	inline naked int call_TraceSQLSetScrollOptions() { __asm { jmp dword ptr [ mProcs + 108 * 4 ] } }
	inline naked int call_TraceSQLSetStmtAttr() { __asm { jmp dword ptr [ mProcs + 109 * 4 ] } }
	inline naked int call_TraceSQLSetStmtAttrW() { __asm { jmp dword ptr [ mProcs + 110 * 4 ] } }
	inline naked int call_TraceSQLSetStmtOption() { __asm { jmp dword ptr [ mProcs + 111 * 4 ] } }
	inline naked int call_TraceSQLSpecialColumns() { __asm { jmp dword ptr [ mProcs + 112 * 4 ] } }
	inline naked int call_TraceSQLSpecialColumnsW() { __asm { jmp dword ptr [ mProcs + 113 * 4 ] } }
	inline naked int call_TraceSQLStatistics() { __asm { jmp dword ptr [ mProcs + 114 * 4 ] } }
	inline naked int call_TraceSQLStatisticsW() { __asm { jmp dword ptr [ mProcs + 115 * 4 ] } }
	inline naked int call_TraceSQLTablePrivileges() { __asm { jmp dword ptr [ mProcs + 116 * 4 ] } }
	inline naked int call_TraceSQLTablePrivilegesW() { __asm { jmp dword ptr [ mProcs + 117 * 4 ] } }
	inline naked int call_TraceSQLTables() { __asm { jmp dword ptr [ mProcs + 118 * 4 ] } }
	inline naked int call_TraceSQLTablesW() { __asm { jmp dword ptr [ mProcs + 119 * 4 ] } }
	inline naked int call_TraceSQLTransact() { __asm { jmp dword ptr [ mProcs + 120 * 4 ] } }
	inline naked int call_TraceVersion() { __asm { jmp dword ptr [ mProcs + 121 * 4 ] } }
	inline naked int call_TraceVSControl() { __asm { jmp dword ptr [ mProcs + 122 * 4 ] } }

#endif // __odbctrac_h__
